apps/blog/urls.py
from django.conf.urls import url
# from .views import goview
from .views import (IndexView, DetailView, CategoryView, TagView, AboutView,
                    SilianView, MySearchView, ArchiveView, TimelineView)

urlpatterns = [
    # url(r'^go/$', goview, name='go'),  # 测试用页面

    url(r'^$', IndexView.as_view(), name='index'),  # 主页，自然排序
    url(r'^hot/$', IndexView.as_view(), {'sort': 'v'}, name='index_hot'),  # 主页，按照浏览量排序
    url(r'^article/(?P<slug>[\w-]+)/$', DetailView.as_view(), name='detail'),  # 文章内容页
    url(r'^category/(?P<slug>[\w-]+)/$', CategoryView.as_view(), name='category'), # 分类
    url(r'^category/(?P<slug>[\w-]+)/hot/$', CategoryView.as_view(), {'sort': 'v'}, # 分类hot
        name='category_hot'),
    url(r'^tag/(?P<slug>[\w-]+)/$', TagView.as_view(), name='tag'),
    url(r'^tag/(?P<slug>[\w-]+)/hot/$', TagView.as_view(), {'sort': 'v'}, name='tag_hot'),
    url(r'^about/$', AboutView, name='about'),  # About页面
    url(r'^timeline/$', TimelineView.as_view(), name='timeline'),  # timeline页面
    url(r'archive/$', ArchiveView.as_view(), name='archive'),  # 归档页面
    url(r'^silian\.xml$', SilianView.as_view(content_type='application/xml'), name='silian'),  # 死链页面
    url(r'^search/$', MySearchView.as_view(), name='search_view'),  # 全文搜索
]

myzone/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import ArticleSitemap, CategorySitemap, TagSitemap
from blog.feeds import AllArticleRssFeed

from rest_framework.routers import DefaultRouter
from api import views as api_views

# rest-framework 的路由分配  这里是list-set别写错了
router = DefaultRouter()
router.register(r'users', api_views.UserListSet)
router.register(r'articles',api_views.ArticleListSet)
router.register(r'tags',api_views.TagListSet)
router.register(r'categorys',api_views.CategoryListSet)
router.register(r'timelines',api_views.TimelineListSet)
router.register(r'toollinks', api_views.ToolLinkListSet)

# 网站地图
sitemaps = {
    'articles': ArticleSitemap,
    'tags': TagSitemap,
    'categories': CategorySitemap
}


urlpatterns = [
    url(r'^adminx/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),  # allauth
    url(r'^accounts/', include('oauth.urls', namespace='oauth')),  # oauth,只展现一个用户登录界面
    url('', include('blog.urls', namespace='blog')),  # blog
    url(r'^comment/',include('comment.urls',namespace='comment')), # comment
    url(r'^tool/', include('tool.urls',namespace='tool')), # tool
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')), # robots
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'), # 网站地图
    url(r'^feed/$', AllArticleRssFeed(), name='rss'),   # rss订阅
    url(r'^api/v1/',include(router.urls,namespace='api')),   # restframework
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 加入这个才能显示media文件

apps/blog/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
import emoji, markdown, re

# Create your models here.


# 文章关键词，用来作为SEO中keywords
class Keyword(models.Model):
    name = models.CharField('文章关键词', max_length=20)

    class Meta:
        verbose_name = '关键词' # 不显示在表里,引用些方法
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name

# 文章标签
class Tag(models.Model):
    name = models.CharField('文章标签', max_length=20)
    slug = models.SlugField(unique=True)
    description = models.TextField('描述', max_length=240, default=settings.SITE_DESCRIPTION,
                                   help_text='用来作为SEO中description,长度参考SEO标准')

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name

    def get_absolute_url(self): # 获得路径
        return reverse('blog:tag', kwargs={'slug': self.slug}) # urls那边路径

        # '''返回当前标签下所有发表的文章列表'''
    def get_article_list(self):
        return Article.objects.filter(tags=self)


# 文章分类
class Category(models.Model):
    name = models.CharField('文章分类', max_length=20)
    slug = models.SlugField(True)
    description = models.TextField('描述', max_length=240, default=settings.SITE_DESCRIPTION,
                                   help_text='用来作为SEO中description,长度参考SEO标准')

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category', kwargs={'slug': self.slug})

    def get_article_list(self):
        return Article.objects.filter(category=self)

# 文章
class Article(models.Model):
    IMG_LINK = '/static/blog/img/summary.png'
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者') # 还有个外键
    title = models.CharField(max_length=150, verbose_name='文章标题')
    summary = models.TextField('文章摘要', max_length=230, default='文章摘要等同于网页description内容，请务必填写...')
    body = models.TextField(verbose_name='文章内容')
    img_link = models.CharField('图片地址', default=IMG_LINK, max_length=255)
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True) # 只加一次
    update_date = models.DateTimeField(verbose_name='修改时间', auto_now=True) # 每次都加
    views = models.IntegerField('阅览量', default=0)
    slug = models.SlugField(unique=True)

    category = models.ForeignKey(Category, verbose_name='文章分类')
    tags = models.ManyToManyField(Tag, verbose_name='标签')
    keywords = models.ManyToManyField(Keyword, verbose_name='文章关键词',
                                      help_text='文章关键词，用来作为SEO中keywords，最好使用长尾词，3-4个足够')

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-create_date']

    def __str__(self):
        return self.title[:20]

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'slug': self.slug}) # urls那边路径

    def body_to_markdown(self): # 文章具体内容
        return markdown.markdown(self.body, extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])

    def update_views(self): # 加一阅读量
        self.views += 1
        self.save(update_fields=['views'])

    def get_pre(self): # 上一篇文章
        return Article.objects.filter(id__lt=self.id).order_by('-id').first()

    def get_next(self): # 下一篇文章
        return Article.objects.filter(id__gt=self.id).order_by('id').first()

# 时间线  建站日志
class Timeline(models.Model):
    COLOR_CHOICE = (
        ('primary', '基本-蓝色'),
        ('success', '成功-绿色'),
        ('info', '信息-天蓝色'),
        ('warning', '警告-橙色'),
        ('danger', '危险-红色')
    )
    SIDE_CHOICE = (
        ('L', '左边'),
        ('R', '右边'),
    )
    STAR_NUM = (
        (1, '1颗星'),
        (2, '2颗星'),
        (3, '3颗星'),
        (4, '4颗星'),
        (5, '5颗星'),
    )
    side = models.CharField('位置', max_length=1, choices=SIDE_CHOICE, default='L')
    star_num = models.IntegerField('星星个数', choices=STAR_NUM, default=3)
    icon = models.CharField('图标', max_length=50, default='fa fa-pencil')
    icon_color = models.CharField('图标颜色', max_length=20, choices=COLOR_CHOICE, default='info')
    title = models.CharField('标题', max_length=100)
    update_date = models.DateTimeField('更新时间')
    content = models.TextField('主要内容')

    class Meta:
        verbose_name = '时间线'
        verbose_name_plural = verbose_name
        ordering = ['update_date']

    def __str__(self):
        return self.title[:20]

    def title_to_emoji(self):
        return emoji.emojize(self.title, use_aliases=True)

    def content_to_markdown(self):
        # 先转换成emoji然后转换成markdown
        to_emoji_content = emoji.emojize(self.content, use_aliases=True)
        return markdown.markdown(to_emoji_content,
                                 extensions=['markdown.extensions.extra', ]
                                 )


# 幻灯片
class Carousel(models.Model):
    number = models.IntegerField('编号', help_text='编号决定图片播放的顺序，图片不要多于5张')
    title = models.CharField('标题', max_length=20, blank=True, null=True, help_text='标题可以为空')
    content = models.CharField('描述', max_length=80)
    img_url = models.CharField('图片地址', max_length=200)
    url = models.CharField('跳转链接', max_length=200, default='#', help_text='图片跳转的超链接，默认#表示不跳转')

    class Meta:
        verbose_name = '图片轮播'
        verbose_name_plural = verbose_name
        ordering = ['number', '-id'] # 编号越小越靠前，添加的时间约晚约靠前

    def __str__(self):
        return self.content[:25]


# 死链
class Silian(models.Model):
    badurl = models.CharField('死链地址', max_length=200, help_text='注意：地址是以http开头的完整链接格式')
    remark = models.CharField('死链说明', max_length=50, blank=True, null=True)
    add_date = models.DateTimeField('提交日期', auto_now_add=True)

    class Meta:
        verbose_name = '死链'
        verbose_name_plural = verbose_name
        ordering = ['-add_date']

    def __str__(self):
        return self.badurl


# 友情链接
class FriendLink(models.Model):
    name = models.CharField('网站名称', max_length=50)
    description = models.CharField('网站描述', max_length=100, blank=True)
    link = models.URLField('友链地址', help_text='请填写http或https开头的完整形式地址')
    logo = models.URLField('网站LOGO', blank=True, help_text='请填写http或https开头的完整形式地址')
    create_date = models.DateTimeField('创建时间', auto_now_add=True)
    is_active = models.BooleanField('是否有效', default=True)
    is_show = models.BooleanField('是否首页展示', default=False)

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name
        ordering = ['create_date']

    def __str__(self):
        return self.name

    def get_home_url(self):
        '''提取友链的主页'''
        u = re.findall(r'(http|https://.*?)/.*?', self.link)
        home_url = u[0] if u else self.link
        return home_url

    def active_to_false(self): # 调用方法改成无效
        self.is_active = False
        self.save(update_fields=['is_active'])

    def show_to_false(self):# 调用方法改成展现首页
        self.is_show = True
        self.save(update_fields=['is_show'])

apps/blog/views.py
from django.shortcuts import get_object_or_404, render
from django.utils.text import slugify
from django.views import generic
from django.conf import settings
from .models import Article, Tag, Category, Timeline, Silian
from django.core.cache import cache

from markdown.extensions.toc import TocExtension  # 锚点的拓展
import markdown
import time, datetime

from haystack.generic_views import SearchView  # 导入搜索视图
from haystack.query import SearchQuerySet



def goview(request):
    return render(request, 'blog/test.html')


# 文章具体内容
class ArchiveView(generic.ListView):
    model = Article
    template_name = 'blog/archive.html'
    context_object_name = 'articles'
    paginate_by = 200
    paginate_orphans = 50


# 主页，自然排序
class IndexView(generic.ListView):
    model = Article
    template_name = 'blog/index.html'
    context_object_name = 'articles'
    paginate_by = getattr(settings, 'BASE_PAGE_BY', None)
    paginate_orphans = getattr(settings, 'BASE_ORPHANS', 0)

    # url传了{'sort': 'v'}进来  浏览量排序
    def get_ordering(self):
        ordering = super(IndexView, self).get_ordering()# 获取到类的内容再覆写这个函数
        sort = self.kwargs.get('sort')
        if sort == 'v': # url传了{'sort': 'v'}进来
            return ('-views', '-update_date', '-id')
        return ordering

# 文章的具体内容
class DetailView(generic.DetailView):
    model = Article
    template_name = 'blog/detail.html'
    context_object_name = 'article'

    def get_object(self):
        obj = super(DetailView, self).get_object()
        # 设置浏览量增加时间判断,同一篇文章两次浏览超过半小时才重新统计阅览量,作者浏览忽略
        u = self.request.user
        ses = self.request.session
        the_key = 'is_read_{}'.format(obj.id)
        is_read_time = ses.get(the_key) # 获取session记录的时间
        if u != obj.author:
            if not is_read_time: # 是不是同一篇文章
                obj.update_views() # 如果不是
                ses[the_key] = time.time() # session记录时间
            else:  # 如果是同一篇文章
                now_time = time.time()
                t = now_time - is_read_time
                if t > 60 * 30:  # 判断是否超过半个小时
                    obj.update_views()
                    ses[the_key] = time.time()

        # 下面的代码中，我选择文章的 ID 和文章更新的日期作为缓存的 key，
        # 这样可以保证当文章更改的时候能够丢弃旧的缓存进而使用新的缓存，而当文章没有更新的时候，
        # 缓存可以一直被调用，知道缓存按照设置的过期时间过期。

        # 使用redis缓存
        # 获取文章更新的时间，判断是否从缓存中取文章的markdown,可以避免每次都转换
        ud = obj.update_date.strftime("%Y%m%d%H%M%S") # 获取文章更新的时间
        md_key = '{}_md_{}'.format(obj.id, ud) # 通过时间和id获取md的key
        cache_md = cache.get(md_key) # 仓库里找有没有这个key
        if cache_md: # 如果有这个key
            md = cache_md # 要转换的内容
        else: # 如果没有建新的
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
                TocExtension(slugify=slugify),
            ]) # 要转换的内容
            cache.set(md_key, md, 60 * 60 * 12) # 设置新的md key
        obj.body = md.convert(obj.body) # 转换要转换的md
        obj.toc = md.toc
        return obj


class CategoryView(generic.ListView):
    model = Article
    template_name = 'blog/category.html'
    context_object_name = 'articles'
    paginate_by = getattr(settings, 'BASE_PAGE_BY', None)
    paginate_orphans = getattr(settings, 'BASE_ORPHANS', 0)

    def get_ordering(self): # 排序
        ordering = super(CategoryView, self).get_ordering()
        sort = self.kwargs.get('sort')
        if sort == 'v':
            return ('-views', '-update_date', '-id')
        return ordering

    def get_queryset(self, **kwargs): # 分类
        queryset = super(CategoryView, self).get_queryset() # 调用父类的 get_queryset 方法获得全部文章列表
        cate = get_object_or_404(Category, slug=self.kwargs.get('slug')) # 使了 slug=self.kwargs.get('slug') 来获取从 URL 捕获的分类 id 值。
        return queryset.filter(category=cate) # 紧接着就对返回的结果调用了 filter 方法来筛选该分类下的全部文章并返回。

    def get_context_data(self, **kwargs):
        context_data = super(CategoryView, self).get_context_data()
        cate = get_object_or_404(Category, slug=self.kwargs.get('slug'))
        context_data['search_tag'] = '文章分类'
        context_data['search_instance'] = cate
        return context_data


class TagView(generic.ListView):
    model = Article
    template_name = 'blog/tag.html'
    context_object_name = 'articles'
    paginate_by = getattr(settings, 'BASE_PAGE_BY', None)
    paginate_orphans = getattr(settings, 'BASE_ORPHANS', 0)

    def get_ordering(self):
        ordering = super(TagView, self).get_ordering()
        sort = self.kwargs.get('sort')
        if sort == 'v':
            return ('-views', '-update_date', '-id')
        return ordering

    def get_queryset(self, **kwargs):
        queryset = super(TagView, self).get_queryset()
        tag = get_object_or_404(Tag, slug=self.kwargs.get('slug'))
        return queryset.filter(tags=tag)

    def get_context_data(self, **kwargs):
        context_data = super(TagView, self).get_context_data()
        tag = get_object_or_404(Tag, slug=self.kwargs.get('slug'))
        context_data['search_tag'] = '文章标签'
        context_data['search_instance'] = tag
        return context_data


def AboutView(request):
    site_date = datetime.datetime.strptime('2018-04-12','%Y-%m-%d')
    return render(request, 'blog/about.html',context={'site_date':site_date})


class TimelineView(generic.ListView):
    model = Timeline
    template_name = 'blog/timeline.html'
    context_object_name = 'timeline_list'


class SilianView(generic.ListView):
    model = Silian
    template_name = 'blog/silian.xml'
    context_object_name = 'badurls'


# 重写搜索视图，可以增加一些额外的参数，且可以重新定义名称
class MySearchView(SearchView):
    context_object_name = 'search_list'
    paginate_by = getattr(settings, 'BASE_PAGE_BY', None)
    paginate_orphans = getattr(settings, 'BASE_ORPHANS', 0)
    queryset = SearchQuerySet().order_by('-views')

apps/blog/templates/blog/category.html
{% extends "blog/base.html" %}
{% load static %}
{% load humanize %}
{% load blog_tags %}

{% block head_title %}{{ search_instance.name }}_{{ search_tag }}{% endblock %}
{% block metas %}
    <meta name="description" content="{{ search_instance.description }}">
    <meta name="keywords" content="{{ search_instance.name }}">
{% endblock %}

{% block base_content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <div class="description bg-white px-3 pt-3 pb-1">
                <p class="float-right mb-0">共<span class="mx-2 text-info">{{ paginator.count }}</span>篇</p>
                <h1 class="f-17"><strong>{{ search_tag }}：{{ search_instance.name }}</strong></h1>
                <p class="f-16">{{ search_instance.description }}</p>
            </div>
            <div class="text-secondary font-weight-bold py-2 f-15 choice">
                {% url 'blog:category' search_instance.slug as base_category %}
                {% url 'blog:category_hot' search_instance.slug as hot_category %}
                <a class="pb-2 {% if request.path == base_category %}active{% endif %}" href="{{ base_category }}">
                    <i class="fa fa-bars mr-1"></i>时间排序</a>
                <a class="pb-2 ml-4 {% if request.path == hot_category %}active{% endif %}" href="{{ hot_category }}">
                    <i class="fa fa-fire mr-1"></i>热度排序</a>
            </div>
            {% load_article_summary articles %}
            {% if is_paginated %}{% load_pages %}{% endif %}
        </div>
        <div class="col-lg-4">
            {% include 'blog/tags/base_right.html' %}
        </div>
    </div>
</div>
{% endblock %}

apps/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags static comment_tags %}
{% load humanize %}

{% block head_title %}{{ article.title }}_{{ article.category }}{% endblock %}
{% block metas %}
    <meta name="description" content="{{ article.summary }}">
    <meta name="keywords" content="{% keywords_to_str article %}">
{% endblock %}


{% block top-file %}
{% if user.is_authenticated %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{% endif %}
<link href="{% static 'blog/css/detail.css' %}?v=20180102.08" rel="stylesheet">
<link href="{% static 'blog/css/github-colorful.css' %}?v=20180102.130" rel="stylesheet">
<link href="{% static 'comment/css/base_comment.css' %}?v=20180114.008" rel="stylesheet">
{% endblock %}

{% block base_content %}
<div class="container">
    <div class="row">
        <div class="col-lg-9">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb bg-white border-0 rounded-0 mb-2 py-2 f-15">
                    <li class="breadcrumb-item">
                        <i class="fa fa-home mr-1"></i><a href="{% url 'blog:index' %}">首页</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{{ article.category.get_absolute_url }}">{{ article.category}}</a>
                    </li>
                    <li class="breadcrumb-item active d-none d-md-block" aria-current="page">{{ article.title }}</li>
                    <li class="breadcrumb-item active d-md-none" aria-current="page">当前位置</li>
                </ol>
            </nav>
            <div class="card rounded-0 border-0" id="article">
                <div class="card-body px-2 px-md-3 pb-0">
                    <h1 class="card-title text-center font-weight-bold text-info">{{ article.title }}</h1>
                    <hr>
                    <div class="text-center f-13">
                        <span class="mx-2" data-toggle="tooltip" data-placement="bottom"
                              title="最后编辑于{{ article.update_date|date:'Y年m月d日' }}">{{ article.create_date }}</span>
                        <span class="mx-2">阅读 {{ article.views }}</span>
                        <a class="mx-2 to-com" href="#comment-block">评论 {% get_comment_count article %}</a>
                    </div>
                    <div class="article-body mt-4 f-17" style="line-height:1.8">
                        {{ article.body|safe }}
                        <p class="font-weight-bold text-info">
                            <i class="fa fa-bullhorn mx-1"></i>
                            原创文章，转载请注明出处：{{ request.build_absolute_uri }}
                        </p>
                    </div>
                    <div class="tag-cloud my-4">
                        {% for tag in article.tags.all %}
                        <a class="tags f-16" href="{{ tag.get_absolute_url }}">{{ tag.name }}</a>
                        {% endfor %}
                    </div>
                    <nav class="more-page f-16">
                        <ul class="pagination justify-content-between">
                            <li class="page-item">
                                {% if article.get_pre %}
                                <a class="d-none d-md-block" href="{{ article.get_pre.get_absolute_url }}"
                                   title="上一篇：{{ article.get_pre.title }}">
                                    <i class="fa fa-chevron-left mr-1"></i>
                                    {{ article.get_pre.title|truncatechars:18 }}
                                </a>
                                <a class="d-md-none" href="{{ article.get_pre.get_absolute_url }}">
                                    <i class="fa fa-chevron-left mr-1"></i>上一篇</a>
                                {% endif %}
                            </li>
                            <li class="page-item">
                                {% if article.get_next %}
                                <a class="d-none d-md-block" href="{{ article.get_next.get_absolute_url }}"
                                   title="下一篇：{{ article.get_next.title }}">
                                    {{ article.get_next.title|truncatechars:18 }}
                                    <i class="fa fa-chevron-right ml-1"></i>
                                </a>
                                <a class="d-md-none" href="{{ article.get_next.get_absolute_url }}">
                                    下一篇<i class="fa fa-chevron-right ml-1"></i>
                                </a>
                                {% endif %}
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="card mt-2 rounded-0 border-0" id="comment-block">
                {% include 'comment/comment_form.html' %}
                {% get_parent_comments article as comment_list %}
                {% include 'comment/comment_list.html' %}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="article-toc d-none d-lg-block f-16">
                {{ article.toc|safe }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block end_file %}
{% if user.is_authenticated %}
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
<script src="{% static 'comment/js/editor.js' %}?v=20180113.05907"></script>
<script src="{% static 'comment/js/activate-power.js' %}?v=20180120"></script>
<script>
var sw=window.screen.width;if(sw>1200){POWERMODE.colorful=true;POWERMODE.shake=false;document.body.addEventListener('input',POWERMODE)};

</script>
{% endif %}
{% endblock %}

apps/blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% load static %}
{% load humanize %}
{% load blog_tags %}




{% block head_title %}Tend to Code_一个使用django和bootstrap搭建的个人博客{% endblock %}
{% block metas %}
    <meta name="description" content="{{ site_description }}">
    <meta name="keywords" content="{{ site_keywords }}">
    <!--站长验证-->
    <meta name="baidu-site-verification" content="YCoD4WTuGF" />
    <meta name="360-site-verification" content="5492df7d63c9ceb707eff60d6cf699e1" />
    <meta name="sogou_site_verification" content="czcxwE2sdj"/>
    <meta name="shenma-site-verification" content="169f4055c7f0323f020d0d238a2bec48_1523704037">
{% endblock %}





{% block base_content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            {% include 'blog/tags/carousel.html' %}
            <div class="text-secondary font-weight-bold py-2 f-15 choice">

                {% url 'blog:index' as base_index %}
                {% url 'blog:index_hot' as hot_index %}

                <a class="pb-2 {% if request.path == base_index %}active{% endif %}" href="{{ base_index }}">
                    <i class="fa fa-bars mr-1"></i>时间排序</a>
                <a class="pb-2 ml-4 {% if request.path == hot_index %}active{% endif %}" href="{{ hot_index }}">
                    <i class="fa fa-fire mr-1"></i>热度排序</a>
            </div>
            {% load_article_summary articles %}
            {% if is_paginated %}{% load_pages %}{% endif %}
        </div>
        <div class="col-lg-4">
            {% include 'blog/tags/base_right.html' %}
        </div>
    </div>
</div>
{% endblock %}

apps/blog/templates/blog/test.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="name" content="Trleo">
  <title>Welcome</title>
  <style>

  </style>
</head>
<body>

<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
<script>

</script>
</body>
</html>