apps/blog/urls.py
from django.conf.urls import url
# from .views import goview
from .views import (IndexView, DetailView, CategoryView, TagView, AboutView,
                    SilianView, MySearchView, ArchiveView, TimelineView)

urlpatterns = [
    # url(r'^go/$', goview, name='go'),  # 测试用页面

    url(r'^$', IndexView.as_view(), name='index'),  # 主页，自然排序
    url(r'^hot/$', IndexView.as_view(), {'sort': 'v'}, name='index_hot'),  # 主页，按照浏览量排序
    url(r'^article/(?P<slug>[\w-]+)/$', DetailView.as_view(), name='detail'),  # 文章内容页
    url(r'^category/(?P<slug>[\w-]+)/$', CategoryView.as_view(), name='category'), # 分类
    url(r'^category/(?P<slug>[\w-]+)/hot/$', CategoryView.as_view(), {'sort': 'v'}, # 分类hot
        name='category_hot'),
    url(r'^tag/(?P<slug>[\w-]+)/$', TagView.as_view(), name='tag'),
    url(r'^tag/(?P<slug>[\w-]+)/hot/$', TagView.as_view(), {'sort': 'v'}, name='tag_hot'),
    url(r'^about/$', AboutView, name='about'),  # About页面
    url(r'^timeline/$', TimelineView.as_view(), name='timeline'),  # timeline页面
    url(r'archive/$', ArchiveView.as_view(), name='archive'),  # 归档页面
    url(r'^silian\.xml$', SilianView.as_view(content_type='application/xml'), name='silian'),  # 死链页面
    url(r'^search/$', MySearchView.as_view(), name='search_view'),  # 全文搜索
]

apps/tool/urls.py
from django.conf.urls import url
from .views import (Toolview, BD_pushview, bd_api_view, BD_pushview_site, bd_api_site, Link_testview,
                    Link_test_api, regexview, regex_api, useragent_view, useragent_api, html_characters)

urlpatterns = [
    url(r'^$', Toolview, name='total'),  # 工具汇总页
    url(r'^baidu-linksubmit/$', BD_pushview, name='baidu_push'),  # 百度主动推送
    url(r'^baidu-linksubmit/ajax/$', bd_api_view, name='baidu_push_api'),  # 百度推送ajax
    url(r'^baidu-linksubmit-for-sitemap/$', BD_pushview_site, name='baidu_push_site'),  # 百度主动推送sitemap
    url(r'^baidu-linksubmit-for-sitemap/ajax/$', bd_api_site, name='baidu_push_api_site'),
    url(r'^link-test/$', Link_testview, name='link_test'),  # 友链检测
    url(r'^link-test/ajax/$', Link_test_api, name='link_test_api'),
    url(r'^regex/$', regexview, name='regex'),  # 正则表达式在线
    url(r'^regex/ajax/$', regex_api, name='regex_api'),
    url(r'^user-agent/$', useragent_view, name='useragent'),  # user-agent生成器
    url(r'^user-agent/ajax/$',useragent_api,name='useragent_api'),
    url(r'^html-special-characters/$',html_characters,name='html_characters'), # HTML特殊字符查询
]

myzone/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import ArticleSitemap, CategorySitemap, TagSitemap
from blog.feeds import AllArticleRssFeed

from rest_framework.routers import DefaultRouter
from api import views as api_views

# rest-framework 的路由分配  这里是list-set别写错了
router = DefaultRouter()
router.register(r'users', api_views.UserListSet)
router.register(r'articles',api_views.ArticleListSet)
router.register(r'tags',api_views.TagListSet)
router.register(r'categorys',api_views.CategoryListSet)
router.register(r'timelines',api_views.TimelineListSet)
router.register(r'toollinks', api_views.ToolLinkListSet)

# 网站地图
sitemaps = {
    'articles': ArticleSitemap,
    'tags': TagSitemap,
    'categories': CategorySitemap
}


urlpatterns = [
    url(r'^adminx/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),  # allauth
    url(r'^accounts/', include('oauth.urls', namespace='oauth')),  # oauth,只展现一个用户登录界面
    url('', include('blog.urls', namespace='blog')),  # blog
    url(r'^comment/',include('comment.urls',namespace='comment')), # comment
    url(r'^tool/', include('tool.urls',namespace='tool')), # tool
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')), # robots
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'), # 网站地图
    url(r'^feed/$', AllArticleRssFeed(), name='rss'),   # rss订阅
    url(r'^api/v1/',include(router.urls,namespace='api')),   # restframework
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 加入这个才能显示media文件

apps/tool/models.py
from django.db import models



# 网站分类, 比如站长工具, 开发工具
class ToolCategory(models.Model):
    name = models.CharField('网站分类名称', max_length=20)
    order_num = models.IntegerField('序号', default=99, help_text='序号可以用来调整顺序，越小越靠前')

    class Meta:
        verbose_name = '工具分类'
        verbose_name_plural = verbose_name
        ordering = ['order_num', 'id']

    def __str__(self):
        return self.name

# 网站名称等具体东西
class ToolLink(models.Model):
    name = models.CharField('网站名称', max_length=20)
    description = models.CharField('网站描述', max_length=100)
    link = models.URLField('网站链接')
    order_num = models.IntegerField('序号', default=99, help_text='序号可以用来调整顺序，越小越靠前')
    category = models.ForeignKey(ToolCategory, verbose_name='网站分类',blank=True,null=True)

    class Meta:
        verbose_name = '推荐工具'
        verbose_name_plural = verbose_name
        ordering = ['order_num', 'id']

    def __str__(self):
        return self.name

apps/tool/views.py
from django.shortcuts import render
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.utils.html import mark_safe
from .apis.bd_push import push_urls, get_urls
from .apis.links_test import Check
from .apis.useragent import get_user_agent

import re
import markdown


# Create your views here.
# tool主界面
def Toolview(request):
    return render(request, 'tool/tool.html')


# 百度主动推送
def BD_pushview(request):
    return render(request, 'tool/bd_push.html')


@require_POST
def bd_api_view(request):
    if request.is_ajax():
        data = request.POST
        url = data.get('url')
        urls = data.get('url_list')
        info = push_urls(url, urls)
        return JsonResponse({'msg': info})
    return JsonResponse({'msg': 'miss'})


# 百度主动推送升级版，提取sitemap链接推送
def BD_pushview_site(request):
    return render(request, 'tool/bd_push_site.html')


@require_POST
def bd_api_site(request):
    if request.is_ajax():
        data = request.POST
        url = data.get('url')
        map_url = data.get('map_url')
        urls = get_urls(map_url)
        if urls == 'miss':
            info = "{'error':404,'message':'sitemap地址请求超时，请检查链接地址！'}"
        elif urls == '':
            info = "{'error':400,'message':'sitemap页面没有提取到有效链接，sitemap格式不规范。'}"
        else:
            info = push_urls(url, urls)
        return JsonResponse({'msg': info})
    return JsonResponse({'msg': 'miss'})


# 友链检测
def Link_testview(request):
    return render(request, 'tool/link_test.html')


@require_POST
def Link_test_api(request):
    if request.is_ajax():
        data = request.POST
        p = data.get('p')
        urls = data.get('urls')
        c = Check(urls, p)
        info = c.run()
        return JsonResponse(info)
    return JsonResponse({'msg': 'miss'})


# 在线正则表达式
def regexview(request):
    return render(request, 'tool/regex.html')


@require_POST
def regex_api(request):
    if request.is_ajax():
        data = request.POST
        texts = data.get('texts')
        regex = data.get('r')
        try:
            lis = re.findall(r'{}'.format(regex), texts)
        except:
            lis = []
        num = len(lis)
        info = '\n'.join(lis)
        result = "匹配到&nbsp;{}&nbsp;个结果：\n".format(num) + "```\n" + info + "\n```"
        result = markdown.markdown(result, extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])
        return JsonResponse({'result': mark_safe(result), 'num': num})
    return JsonResponse({'msg': 'miss'})


# 生成请求头
def useragent_view(request):
    return render(request, 'tool/useragent.html')


@require_POST
def useragent_api(request):
    if request.is_ajax():
        data = request.POST
        d_lis = data.get('d_lis') # 获取并命名
        os_lis = data.get('os_lis')
        n_lis = data.get('n_lis')
        d = d_lis.split(',') if len(d_lis) > 0 else None
        os = os_lis.split(',') if len(os_lis) > 0 else None
        n = n_lis.split(',') if len(n_lis) > 0 else None
        result = get_user_agent(os=os, navigator=n, device_type=d)
        return JsonResponse({'result': result})
    return JsonResponse({'msg': 'miss'})


# HTML特殊字符对照表
def html_characters(request):
    return render(request, 'tool/characters.html')

apps/tool/templates/tool/base_tool.html
{% extends "blog/base.html" %}
{% load static %}

{% block top-file %}
<link href="{% static 'tool/css/tool.css' %}?v=20180107.074679" rel="stylesheet">
{% endblock %}

{% block base_content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 f-16">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb bg-white border-0 rounded-0 mb-2 py-2 f-15">
                    <li class="breadcrumb-item">
                        <i class="fa fa-home mr-1"></i><a href="{% url 'blog:index' %}">首页</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'tool:total' %}">在线工具</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">{% block tool_name %}{% endblock %}</li>
                </ol>
            </nav>
            <div class="card rounded-0 border-0 p-2 p-lg-3">
                {% block left_content %}{% endblock %}
            </div>
        </div>
        <div class="col-lg-4 d-none d-lg-block">
            {% include 'tool/tags/tool_list.html' %}
        </div>
    </div>
</div>
{% endblock %}

{% block end_file %}
<script src="{% static 'tool/js/tool.js'%}?v=20180105.40757"></script>
{% block end_f %}{% endblock %}
{% endblock %}

apps/tool/templates/tool/bd_push.html
{% extends "tool/base_tool.html" %}
{% load static %}

{% block head_title %}百度主动推送工具在线使用，实时主动提交网站链接，加快网站内容抓取_站长工具{% endblock %}
{% block metas %}
    <meta name="description" content="百度主动推送工具，是一个在线实时推送链接的站长工具，这个工具调用百度站长平台提供的主动提交API接口，自动批量向百度推送网站链接，使网页更快的被百度收录，加快抓取速度和提升效率。">
    <meta name="keywords" content="百度主动推送工具,自动提交,站长工具,百度收录,实时提交,在线工具">
{% endblock %}

{% block tool_name %}百度主动推送工具{% endblock %}
{% block left_content %}
<div class="card-body p-0">
    <h3 class="card-title pl-2 title-info">工具说明：</h3>
    <ul>
        <li>本工具使用的百度站长平台官方提供的推送接口</li>
        <li>工具的作用是批量提交网站链接，主动推送给百度收录，具体作用请查看
            <a class="text-info" href="https://ziyuan.baidu.com/linksubmit/index" target="_blank">官方说明</a>
        </li>
        <li>首先将百度站长提供的“接口调用地址”复制到下面表单中，然后按示例输入自己网站要提交的链接，点击提交按钮即可看到返回的信息</li>
        <li>本工具适合网站大部分链接已经被百度收录的老站使用，新站建议使用
            <a class="text-info" href="{% url 'tool:baidu_push_site' %}">Sitemap主动推送</a> 可以直接批量提交整站链接
        </li>
    </ul>
</div>
<div class="mb-3">
    <div class="form-group">
        <label>接口调用地址：</label>
        <input type="url" class="form-control rounded-0" id="form-url"
               placeholder="例：http://data.zz.baidu.com/urls?site=www.example.com&token=NpU0****tTQAlBV"
               required>
        <small class="form-text text-muted">注：请填写百度站长平台提供给您的接口调用地址</small>
    </div>
    <div class="form-group">
        <label>网址链接：</label>
        <textarea class="form-control rounded-0" id="form-urls" rows="5" required
                  placeholder="示例如下：&#10;http://www.example.com/mip/&#10;http://www.example.com/mip/1.html&#10;http://www.example.com/mip/2.php"></textarea>
        <small class="form-text text-muted">注：提交的链接的域名必须与接口中site保持一直才能推送成功</small>
    </div>
    <button type="submit" class="btn btn-info btn-sm rounded-0" id="start-push">开始推送</button>
</div>
<div class="card mb-3 rounded-0">
    <div class="card-header text-center text-info font-weight-bold py-2">推送结果</div>
    <div class="card-body push-result text-center py-3">结果显示区</div>
</div>
<h3 class="mb-3 pl-2 title-info">推送结果参数解读：</h3>
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home"
           aria-selected="true">推送成功</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile"
           aria-selected="false">推送失败</a>
    </li>
</ul>
<div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
        <p class="my-1 text-muted">状态码为200，可能返回以下字段：</p>
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th scope="col">字段</th>
                <th scope="col">是否必传</th>
                <th scope="col">参数类型</th>
                <th scope="col">说明</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row">remain</th>
                <td>是</td>
                <td>int</td>
                <td>当天剩余的可推送url条数</td>
            </tr>
            <tr>
                <th scope="row">success</th>
                <td>是</td>
                <td>int</td>
                <td>成功推送的url条数</td>
            </tr>
            <tr>
                <th scope="row">not_same_site</th>
                <td>否</td>
                <td>array</td>
                <td>由于不是本站url而未处理的url列表</td>
            </tr>
            <tr>
                <th scope="row">not_valid</th>
                <td>否</td>
                <td>array</td>
                <td>不合法的url列表</td>
            </tr>
            </tbody>
        </table>
        <p class="my-1 text-muted">成功返回示例：</p>
        <div class="codehilite">
            <pre>
{
    &quot;remain&quot;:4999998,
    &quot;success&quot;:2,
    &quot;not_same_site&quot;:[],
    &quot;not_valid&quot;:[]
}
            </pre>
        </div>
    </div>
    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
        <p class="my-1 text-muted">状态码为4xx，返回字段有：</p>
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th scope="col">字段</th>
                <th scope="col">是否必传</th>
                <th scope="col">参数类型</th>
                <th scope="col">说明</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row">error</th>
                <td>是</td>
                <td>int</td>
                <td>错误码，与状态码相同</td>
            </tr>
            <tr>
                <th scope="row">message</th>
                <td>是</td>
                <td>string</td>
                <td>错误描述</td>
            </tr>
            </tbody>
        </table>
        <p class="my-1 text-muted">失败返回示例：</p>
        <div class="codehilite">
            <pre>
{
    &quot;error&quot;:401,
    &quot;message&quot;:&quot;token is not valid&quot;
}
            </pre>
        </div>
    </div>
</div>
{% endblock %}

{% block end_f %}
<script>
$('#start-push').click(function() {
	push_spider("{{ csrf_token }}", "{% url 'tool:baidu_push_api' %}");
})

</script>
{% endblock %}

apps/tool/templates/tool/bd_push_site.html
{% extends "tool/base_tool.html" %}
{% load static %}

{% block head_title %}Sitemap主动推送，百度主动推送工具升级版，加快网站内容抓取_站长工具{% endblock %}
{% block metas %}
<meta name="description" content="Sitemap主动推送是百度主动推送工具的升级版，可以在线实时自动提交链接，首先使用正则表达式批量抓取网站sitemap页面所有链接，然后调用百度站长平台的主动推送接口，批量推送链接，加快抓取速度和百度收录效率。">
<meta name="keywords" content="百度主动推送,站长工具,在线工具,sitemap,自动提交,百度收录,实时提交">
{% endblock %}

{% block tool_name %}Sitemap主动推送{% endblock %}
{% block left_content %}
<div class="card-body p-0">
    <h3 class="card-title pl-2 title-info">工具说明：</h3>
    <ul>
        <li>这个Sitemap主动推送工具是百度主动推送工具的升级版</li>
        <li>本工具的作用是抓取网站sitemap页面中所有的链接，然后使用百度站长官方提供的推送接口主动推送链接给百度收录，百度主动推送的作用请查看
            <a class="text-info" href="https://ziyuan.baidu.com/linksubmit/index" target="_blank">官方说明</a>
        </li>
        <li>首先将百度站长提供的“接口调用地址”复制到下面表单中，然后将自己网站的sitemap页面的地址复制到对应表单中，点击提交按钮即可看到返回的信息</li>
        <li>本工具适合新站或百度收录量比较少的老站使用，对于网站大部分链接已经被百度收录的老站建议使用
            <a class="text-info" href="{% url 'tool:baidu_push' %}">百度主动推送工具</a> 实时提交新建链接
        </li>
    </ul>
</div>
<div class="mb-3">
    <div class="form-group">
        <label>接口调用地址：</label>
        <input type="url" class="form-control rounded-0" id="form-url"
               placeholder="例：http://data.zz.baidu.com/urls?site=www.example.com&token=NpU0****tTQAlBV"
               required>
        <small class="form-text text-muted">注：请填写百度站长平台提供给您的接口调用地址</small>
    </div>
    <div class="form-group">
        <label>Sitemap地址：</label>
        <input type="url" class="form-control rounded-0" id="form-sitemap"
               placeholder="例：http://www.example.com/sitemap.xml"
               required>
        <small class="form-text text-muted">注：规范的sitemap网页的链接应该包含在&lt;loc&gt;标签中，否则无法提取到链接</small>
    </div>
    <button type="submit" class="btn btn-info btn-sm rounded-0" id="start-push">开始推送</button>
</div>
<div class="card mb-3 rounded-0">
    <div class="card-header text-center text-info font-weight-bold py-2">推送结果</div>
    <div class="card-body push-result text-center py-3">结果显示区</div>
</div>
<h3 class="mb-3 pl-2 title-info">推送结果参数解读：</h3>
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home"
           aria-selected="true">推送成功</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile"
           aria-selected="false">推送失败</a>
    </li>
</ul>
<div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
        <p class="my-1 text-muted">状态码为200，可能返回以下字段：</p>
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th scope="col">字段</th>
                <th scope="col">是否必传</th>
                <th scope="col">参数类型</th>
                <th scope="col">说明</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row">remain</th>
                <td>是</td>
                <td>int</td>
                <td>当天剩余的可推送url条数</td>
            </tr>
            <tr>
                <th scope="row">success</th>
                <td>是</td>
                <td>int</td>
                <td>成功推送的url条数</td>
            </tr>
            <tr>
                <th scope="row">not_same_site</th>
                <td>否</td>
                <td>array</td>
                <td>由于不是本站url而未处理的url列表</td>
            </tr>
            <tr>
                <th scope="row">not_valid</th>
                <td>否</td>
                <td>array</td>
                <td>不合法的url列表</td>
            </tr>
            </tbody>
        </table>
        <p class="my-1 text-muted">成功返回示例：</p>
        <div class="codehilite">
            <pre>
{
    &quot;remain&quot;:4999998,
    &quot;success&quot;:2,
    &quot;not_same_site&quot;:[],
    &quot;not_valid&quot;:[]
}
            </pre>
        </div>
    </div>
    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
        <p class="my-1 text-muted">状态码为4xx，返回字段有：</p>
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th scope="col">字段</th>
                <th scope="col">是否必传</th>
                <th scope="col">参数类型</th>
                <th scope="col">说明</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row">error</th>
                <td>是</td>
                <td>int</td>
                <td>错误码，与状态码相同</td>
            </tr>
            <tr>
                <th scope="row">message</th>
                <td>是</td>
                <td>string</td>
                <td>错误描述</td>
            </tr>
            </tbody>
        </table>
        <p class="my-1 text-muted">失败返回示例：</p>
        <div class="codehilite">
            <pre>
{
    &quot;error&quot;:401,
    &quot;message&quot;:&quot;token is not valid&quot;
}
            </pre>
        </div>
    </div>
</div>
{% endblock %}

{% block end_f %}
<script>
$('#start-push').click(function() {
	site_push_spider("{{ csrf_token }}", "{% url 'tool:baidu_push_api_site' %}");
})

</script>
{% endblock %}

apps/tool/templates/tool/tool.html
{% extends "blog/base.html" %}
{% load static %}
{% load humanize %}
{% load blog_tags %}

{% block head_title %}在线工具，提升工作效率{% endblock %}
{% block metas %}
<meta name="description" content="在线工具，提供站长工具包括百度主动推送工具、友链检测、正则表达式工具等，方便进行批量操作，提高工作效率，工具持续增加中">
<meta name="keywords" content="在线工具,SEO工具,站长工具,爬虫工具">
{% endblock %}


{% block top-file %}
<link href="{% static 'tool/css/tool.css' %}?v=20180107.08" rel="stylesheet">
{% endblock %}

{% block base_content %}
<div class="container">
    <div class="row tool-list">
        <div class="col-md-6 col-lg-4 col-xl-3 px-lg-2 mb-3">
            <div class="card">
                <div class="card-header p-2 tool-header">
                    <a href="{% url 'tool:baidu_push' %}">
                        <img class="w-25 float-left mr-2" src="{% static 'blog/img/baidu-2.png' %}"
                             alt="百度主动推送工具">
                        <h2 class="card-title">百度主动推送工具</h2>
                    </a>
                    <p class="mb-0">[站长工具]</p>
                </div>
                <div class="card-body p-3 tool-des">
                    <p class="card-text">调用百度站长提供的主动推送接口批量提交链接，提升网站收录效率，老站必备</p>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-4 col-xl-3 px-lg-2 mb-3">
            <div class="card">
                <div class="card-header p-2 tool-header">
                    <a href="{% url 'tool:baidu_push_site' %}">
                        <img class="w-25 float-left mr-2" src="{% static 'blog/img/map.png' %}"
                             alt="Sitemap主动推送">
                        <h2 class="card-title">Sitemap主动推送</h2>
                    </a>
                    <p class="mb-0">[站长工具]</p>
                </div>
                <div class="card-body p-3 tool-des">
                    <p class="card-text">抓取Sitemap页面所有链接，调用百度主动推送接口，主动批量提交网站链接，新站必备</p>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-4 col-xl-3 px-lg-2 mb-3">
            <div class="card">
                <div class="card-header p-2 tool-header">
                    <a href="{% url 'tool:link_test' %}">
                        <img class="w-25 float-left mr-2" src="{% static 'blog/img/link-2.png' %}"
                             alt="友链检测工具">
                        <h2 class="card-title">友链检测工具</h2>
                    </a>
                    <p class="mb-0">[站长工具]</p>
                </div>
                <div class="card-body p-3 tool-des">
                    <p class="card-text">批量检查友情链接状态，查看友链的反链有效性，便于站长对无效的友链进行删除和调整</p>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-4 col-xl-3 px-lg-2 mb-3">
            <div class="card">
                <div class="card-header p-2 tool-header">
                    <a href="{% url 'tool:regex' %}">
                        <img class="w-25 float-left mr-2" src="{% static 'blog/img/regex.png' %}"
                             alt="在线正则表达式">
                        <h2 class="card-title">在线正则表达式</h2>
                    </a>
                    <p class="mb-0">[开发工具]</p>
                </div>
                <div class="card-body p-3 tool-des">
                    <p class="card-text">正则表达式在线工具，使用正则表达式的规则提取信息，所有语言规则通用</p>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-4 col-xl-3 px-lg-2 mb-3">
            <div class="card">
                <div class="card-header p-2 tool-header">
                    <a href="{% url 'tool:useragent' %}">
                        <img class="w-25 float-left mr-2" src="{% static 'blog/img/chrome.png' %}"
                             alt="User-Agent生成器">
                        <h2 class="card-title">User-Agent生成器</h2>
                    </a>
                    <p class="mb-0">[爬虫工具]</p>
                </div>
                <div class="card-body p-3 tool-des">
                    <p class="card-text">网页请求头在线生成器，自动生成各种平台和浏览器的请求头User-Agent</p>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-4 col-xl-3 px-lg-2 mb-3">
            <div class="card">
                <div class="card-header p-2 tool-header">
                    <a href="{% url 'tool:html_characters' %}">
                        <img class="w-25 float-left mr-2" src="{% static 'blog/img/html.png' %}"
                             alt="HTML特殊字符对照表">
                        <h2 class="card-title">HTML特殊字符</h2>
                    </a>
                    <p class="mb-0">[开发工具]</p>
                </div>
                <div class="card-body p-3 tool-des">
                    <p class="card-text">HTML常用字符查询表，HTML特殊字符对照表</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}